name: Release Whisper.CPP

on:
  push:
    branches:
      - '33n-build'
#    paths:
#      - '.devops/33n-run.Dockerfile'
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    name: Build & push image to ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Short SHA as Environment Variable
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Build and Push
        uses: kciter/aws-ecr-action@v5
        env:
          repo: whisper_cpp
          build_github_token: ${{ secrets.GIT_TOKEN_CODE_DEPLOY }}
        with:
          access_key_id: ${{ secrets.AWS_PROD_ECR_AKI }}
          secret_access_key: ${{ secrets.AWS_PROD_ECR_SAK }}
          account_id: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
          repo: ${{ env.repo }}
          region: eu-west-2
          tags: run-latest,run-${{ env.SHORT_SHA }}
          dockerfile: .devops/33n-run.Dockerfile
          extra_build_args: --build-arg BASE_CUDA_DEV_CONTAINER=${{ secrets.AWS_PROD_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/${{ env.repo }}:build-latest
