name: Release Whisper.CPP

on:
  push:
    branches:
      - '33n-build'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  release_tag_cpp:
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.tagging.outputs.new_tag }}

    name: Tag version CPP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

  build_and_push_image:
    needs: [release_tag_cpp]
    runs-on: ubuntu-latest

    name: Build & push image to ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Short SHA as Environment Variable
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Build and Push
        uses: kciter/aws-ecr-action@v5
        env:
          repo: whisper_cpp
          build_github_token: ${{ secrets.GIT_TOKEN_CODE_DEPLOY }}
        with:
          access_key_id: ${{ secrets.AWS_PROD_ECR_AKI }}
          secret_access_key: ${{ secrets.AWS_PROD_ECR_SAK }}
          account_id: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
          repo: ${{ env.repo }}
          region: eu-west-2
          tags: build-latest,build-$SHORT_SHA
          dockerfile: .devops/33n-build.Dockerfile
