name: Release Whisper.CPP

on:
  push:
    branches:
      - '33n-build'
    paths:
      - '.devops/33n-run.Dockerfile'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

  build_and_push_image:
    needs: [build]
    runs-on: ubuntu-latest

    name: Build & push image to ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push
        uses: kciter/aws-ecr-action@v5
        env:
          repo: whisper_cpp
          build_github_token: ${{ secrets.GIT_TOKEN_CODE_DEPLOY }}
        with:
          access_key_id: ${{ secrets.AWS_PROD_ECR_AKI }}
          secret_access_key: ${{ secrets.AWS_PROD_ECR_SAK }}
          account_id: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
          repo: ${{ env.repo }}
          region: eu-west-2
          tags: run-latest,run-${{needs.release_tag_cpp.outputs.output}}
          dockerfile: .devops/33n-run.Dockerfile
          extra_build_args: --build-arg BASE_CUDA_DEV_CONTAINER=${{ env.repo }}:build-latest
